### ISSUE TITLE
Project Submission: ff4s

### ISSUE THREAD

**Issue by buntec** [typelevel/governance#101]
### Project Name
[ff4s](https://github.com/buntec/ff4s)

### Project Short Description
Yet another front-end framework for Scala.js. Built on top of CE3 and fs2.

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

### Project Management

Typelevel projects are required to have an appropriate Code of Conduct. The [Scala Code of Conduct](https://typelevel.org/code-of-conduct) is a good option, but not specifically required. Before submitting a project for inclusion, please ensure that a pointer to its Code of Conduct is clearly linked from its README, CODE_OF_CONDUCT.md, or website.

- [x] This project's Code of Conduct can be found at https://github.com/buntec/ff4s/blob/main/CODE_OF_CONDUCT.md

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria). Please make sure that the project's license is on the approved list.

- [x] This project's license can be found at https://github.com/buntec/ff4s/blob/main/LICENSE.txt

### Additional Notes
Suggested for submission by @armanbilge.

**Comment by rossabaker** [comment]
Thanks, @buntec!

@typlevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.  Voting is open three business days (through Friday, April 28) and until quorum (7) is reached.

**Comment by valencik** [comment]
Hey @buntec, thanks for submitting this.
I notice you list calico as an inspiration, for my own curiosity, could you say a bit about how ff4s differs?

I'm looking forward to playing with this. :)

**Comment by buntec** [comment]
Hey @valencik,

That's a great (and also difficult) question! I'm by no means an expert on UI frameworks and patterns so please take this with a grain of salt. I'll surely get things wrong, in which case I firmly rely on @armanbilge to correct me ;). 

Let me first say that all of the mentioned Scala.js front-end libs are great and I certainly don't claim that ff4s is better than any one of them. The solution space for UI libs is huge (evidenced by the proliferation of such libs) and picking one over another is, in my opinion, a matter of trade-offs and taste!

With that out of the way, I think Laminar, Outwatch and Calico all differ significantly from ff4s. The architecture of ff4s is closer to [Elm](https://guide.elm-lang.org/architecture/) (and hence also [Tyrian](https://tyrian.indigoengine.io/)) and [Redux](https://redux.js.org/tutorials/fundamentals/part-2-concepts-data-flow): there is a single store holding global immutable state (the `Model` in Elm), a set of actions that describe (effectful) state updates (`Msg`/`Cmd` in Elm), and finally there is a rendering function (the "view") which is simply a pure function of the state. In particular, the data flow is unidirectional. Laminar, Calico and Outwatch are more flexible in that there usually isn't a single, global state container. Instead, each component can hold its own state, but may also have access to the state of other components in an ad-hoc fashion. Moreover, state updates don't have to be coordinated by a store. I think there are pros and cons to both approaches. 

In terms of the implementation, the Elm/Redux pattern is a natural fit for virtual DOMs. Indeed, since every state update is global, we want to make sure that we only update (i.e. mutate) the part of the (real) DOM that's actually affected. VDOMs accomplish this using a diffing algorithm. On the other hand, Calico doesn't *need* a VDOM because state updates are local and each component is responsible for updating its part of the DOM. That's why components in Calico "return" real DOM elements, while components in ff4s "return" VDOM elements. Finally, (and I hope this is a fair assessment) what distinguishes ff4s from all other mentioned libs except Calico is that it is built on top of cats-effect and fs2 primitives and thus *feels* native to the ecosystem. In fact, this has been my main motivation for embarking on this project! Although completely anecdotal, we've been using ff4s quite extensively at my workplace, and people who know and love cats-effect and fs2 have taken to it very naturally.

I hope this helps!

**Comment by rossabaker** [comment]
That's quorum and unanimously confirmed.  Next steps are tracked in #104.
