### ISSUE TITLE
release `download-java` action on GH marketplace

### ISSUE THREAD

**Issue by samspills** [typelevel/governance#102]
Initially requested here: https://github.com/typelevel/download-java/issues/22

Steps
- [ ] accept the marketplace developer agreement
  - for reference, [these are the terms](https://docs.github.com/en/site-policy/github-terms/github-marketplace-developer-agreement)
- [ ] ~draw the rest of the owl~ release the action, with the `Publish this release to the GitHub Marketplace` box checked

I can accept the terms, but wanted to give everyone a chance to look over them if they so desire, cc @typelevel/steering

**Comment by rossabaker** [comment]
Does anybody have a summary of responsibilities and liabilities compared to the status quo?  Those terms are a lot to digest.  I want to help, but I also don't want to get sued by a certain JDK provider whose CEO bought a Hawai`ian island.

**Comment by jducoeur** [comment]
Yow -- yeah, while some of that is just standard boilerplate, there's a lot there we'll need to understand properly.

**Comment by valencik** [comment]
Perhaps a helpful heuristic, the ASF signed it: https://issues.apache.org/jira/browse/LEGAL-537

**Comment by rossabaker** [comment]
Does it get signed as Typelevel?  I am struggling with who the "Developer" is, since we're neither an individual nor a company.

> "Developer" means you, and you are the company or individual who has created the software, content, and digital materials for use in connection with GitHub and accessible via Marketplace.

I read through it, and I don't see anything atypical, nor can I find anybody complaining about it online.

**Comment by rossabaker** [comment]
Secondhand legal advice from a colleague asking an expert:

> The feedback I got was that if there is a legal structure in place the governance document needs to specify who/roles allowed to enter into agreements with 3rd parties and any of those individuals can sign. If there is no legal structure it's not really legally possible to sign an agreement without getting everyone to sign.

It would be interesting to find examples of another organization like us in the program: more than a person, less than a corporation.

**Comment by armanbilge** [comment]
As of sbt-typelevel [v0.5.0-RC1](https://github.com/typelevel/sbt-typelevel/releases/tag/v0.5.0-RC1) we are no longer using the `download-java` action, so it is effectively deprecated. If somebody wants to continue to use it outside of sbt-typelevel they could always fork the repo and publish to marketplace themselves?

**Comment by armanbilge** [comment]
Upstream issue is closed, so we can close this too.
- https://github.com/typelevel/download-java/issues/22

**Comment by rossabaker** [comment]
The abstract question may come up again, but agree the specific is addressed.
