### ISSUE TITLE
Project Submission: fs2-aes

### ISSUE THREAD

**Issue by jwojnowski** [typelevel/governance#107]
### Project Name
fs2-aes

### Project Short Description
Micro library providing AES encryption/decryption of `fs2.Stream[F, Byte]`.

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

### Project Management

Typelevel projects are required to have an appropriate Code of Conduct. The [Scala Code of Conduct](https://typelevel.org/code-of-conduct) is a good option, but not specifically required. Before submitting a project for inclusion, please ensure that a pointer to its Code of Conduct is clearly linked from its README, CODE_OF_CONDUCT.md, or website.

- [x] This project's Code of Conduct can be found at [https://github.com/jwojnowski/fs2-aes/blob/main/CODE_OF_CONDUCT.md](https://github.com/jwojnowski/fs2-aes/blob/main/CODE_OF_CONDUCT.md)

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria). Please make sure that the project's license is on the approved list.

- [x] This project's license can be found at [https://github.com/jwojnowski/fs2-aes/blob/main/LICENSE](https://github.com/jwojnowski/fs2-aes/blob/main/LICENSE)

### Additional Notes
Thanks to @armanbilge for [suggesting](https://github.com/typelevel/fs2/pull/3222#issuecomment-1547028787) this 🙂

**Comment by rossabaker** [comment]
Nice, thanks for sharing.  Sorry for the slow reply, as I've been on PTO.

@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.  Voting is open three business days (through Tuesday, May 24) and until quorum (7) is reached.

**Comment by rossabaker** [comment]
@typelevel/steering : bump

**Comment by rossabaker** [comment]
Approved with a quorum (7) and majority (100%). :tada:

Next steps are tracked in #109.
