### ISSUE TITLE
Project Submission: Grackle GraphQL

### ISSUE THREAD

**Issue by milessabin** [typelevel/governance#110]
### Project Name
Grackle GraphQL

### Project Short Description
Grackle is a purely functional GraphQL engine built for the Typelevel stack, designed for applications built with Cats, Cats Effect, FS2, http4s, Doobie and Skunk.

The project is maintained on [github](https://github.com/gemini-hlsw/gsp-graphql) and published under an open source licence for Scala 2 and 3; and JVM, JS and native targets.

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [x] Organization Project
- [ ] Affiliate Project

### Project Management

+ The project adheres to the [Scala Code of Conduct](https://www.scala-lang.org/conduct/).
+ The project is licensed under the [3 Clause BSD license](https://opensource.org/licenses/BSD-3-Clause). (If it is acceptable to the current contributors we will move the license to [Apache 2](https://opensource.org/license/apache-2-0/)).

Both the above are linked to from the projects [README](https://github.com/gemini-hlsw/gsp-graphql/blob/main/README.md).

+ The project has a `-dev` channel on the Typelevel discord. As part of the move we would like to create a complementary user channel.

### About the Project
The project was initially created by [AURA/Gemini](https://www.aura-astronomy.org/centers/nsfs-oir-lab/gemini-observatory/) to support the end-user and internal interface for all components of their next-generation observatory control system.

Shortly after its inception it was adopted by [ITV](http://itv.com) for its ITVX streaming service where it now delivers content-related metadata to all forms of streaming client and to distribution partners; and article metadata for the ITV news site.

A significant motivation for its creation was the lack of alternatives which integrated smoothly with the broader Typelevel ecosystem. As such it has been built with a foundation in cats, cats-effect, fs2, and with special attention to backing GraphQL interfaces with functional database abstractions such as Typelevel's doobie and skunk.

GraphQL is a query language for typed APIs. Talk of languages and types leads naturally to thinking about evaluating GraphQL queries as involving type checking, interpretation and compilation. A common functional approach to compilation and interpretation is the "programs as values" model, and this is model that Grackle adopts.

Grackle compiles GraphQL queries into programs in a simple internal query language, type checks those programs, transforms them in a variety of ways (for instance to map a GraphQL query onto an efficient SQL query, or to compose several independent APIs into a single uniform API) and then interprets the resulting program to execute the query.

### Motivation for this submission

+ Grackle is built on the Typelevel stack.
+ It brings an important capability to the Typelevel ecosystem.
+ It has been developed and battle tested at several organisations, but doesn't currently have an independent home.
+ It would benefit from the wider range of user needs and contributions that exposure via the Typelevel ecosystem would bring.

**Comment by jducoeur** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain. Voting is open three business days (through Friday, June 23) and until quorum (7) is reached.

**Comment by rossabaker** [comment]
Thanks, @jducoeur.  Apologies, I've had a tumultuous week and this is the first it floated onto my GitHub notifications.

We're already at quorum, and it only needs one more :+1: to assure the 3/4 vote and move this along before Friday.  It would be nice, after I introduced a delay being asleep at the wheel.

**Comment by rossabaker** [comment]
Approved with 9 👍, which is both a quorum and enough to assure the supermajority.  Migration steps are tracked in #111.

**Comment by milessabin** [comment]
Thanks! :tada:
