### ISSUE TITLE
Project Submission: cats-stm

### ISSUE THREAD

**Issue by TimWSpence** [typelevel/governance#118]
### Project Name
[Cats STM](https://github.com/TimWSpence/cats-stm)

### Project Short Description
A STM implementation for Cats Effect 

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

### Project Management

Typelevel projects are required to have an appropriate Code of Conduct. The [Scala Code of Conduct](https://typelevel.org/code-of-conduct) is a good option, but not specifically required. Before submitting a project for inclusion, please ensure that a pointer to its Code of Conduct is clearly linked from its README, CODE_OF_CONDUCT.md, or website.

- [x] This project's Code of Conduct can be found at https://github.com/TimWSpence/cats-stm/blob/main/CODE_OF_CONDUCT.md

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria). Please make sure that the project's license is on the approved list.

- [x] This project's license can be found at https://github.com/TimWSpence/cats-stm/blob/main/LICENSE.txt

### Additional Notes
Sorry, I've been meaning to do this for ages. I _think_ I've filled this in correctly. Please let me know if I missed anything!

**Comment by valencik** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.

Voting is open three business days (through Tuesday, November 21) and until quorum (7) is reached.

**Comment by valencik** [comment]
Thanks for submitting this @TimWSpence 🎉 
I've edited your issue just to make the project name link to the repo for easy clicking.

cats-stm seems like a natural fit :)

**Comment by TimWSpence** [comment]
Thanks @valencik! :)

**Comment by valencik** [comment]
We've hit quorum and the vote is approved, thanks folks.

Migration issue is here: https://github.com/typelevel/governance/issues/119
