### ISSUE TITLE
Project Submission: ldbc

### ISSUE THREAD

**Issue by takapi327** [typelevel/governance#121]
### Project Name
[ldbc](https://github.com/takapi327/ldbc)

### Project Short Description
Pure functional JDBC layer with Cats Effect 3 and Scala 3

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

### Project Management

Typelevel projects are required to have an appropriate Code of Conduct. The [Scala Code of Conduct](https://typelevel.org/code-of-conduct) is a good option, but not specifically required. Before submitting a project for inclusion, please ensure that a pointer to its Code of Conduct is clearly linked from its README, CODE_OF_CONDUCT.md, or website.

- [x] This project's Code of Conduct can be found at [CODE_OF_CONDUCT](https://github.com/takapi327/ldbc/blob/master/CODE_OF_CONDUCT.md)

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria). Please make sure that the project's license is on the approved list.

- [x] This project's license can be found at [LICENSE](https://github.com/takapi327/ldbc/blob/master/LICENSE)

### Additional Notes
ldbc is version 1.0.0 or earlier and is still under development.
Also, as I am new to OSS development, there may be some incorrectly written code.
Therefore, the project is still in its infancy, and it cannot be said to be operating in a stable manner in terms of performance, etc.

By participating in the typelevel community, we would like to receive opinions from various people and improve it.

Please let me know if I missed anything!

**Comment by valencik** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.

Because of the time of year, let's have voting open for five business days (through Friday, December 22) and until quorum (7) is reached.

**Comment by valencik** [comment]
We've hit quorum and the vote is approved, thanks folks.
(and sorry for the delays. holidays and whatnot)

Migration issue is here: https://github.com/typelevel/governance/issues/123
