### ISSUE TITLE
Project Submission: systemfw/upperbound

### ISSUE THREAD

**Issue by SystemFw** [typelevel/governance#122]
### Project Name
`upperbound`

### Project Short Description
A rate limiter with no bursts, prioritised jobs, and dynamic control over rate and concurrency.

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

### Project Management

Typelevel projects are required to have an appropriate Code of Conduct. The [Scala Code of Conduct](https://typelevel.org/code-of-conduct) is a good option, but not specifically required. Before submitting a project for inclusion, please ensure that a pointer to its Code of Conduct is clearly linked from its README, CODE_OF_CONDUCT.md, or website.

- [x] This project's Code of Conduct can be found at [CoC](https://github.com/SystemFw/upperbound/blob/main/CODE_OF_CONDUCT.md)

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria). Please make sure that the project's license is on the approved list.

- [x] This project's license can be found at [License](https://github.com/SystemFw/upperbound/blob/main/LICENSE)

### Additional Notes

`upperbound` has been a pretty standard recommendation for a while, so I think the extra visibility would be helpful for users

**Comment by valencik** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.

Because of the time of year, let's have voting open for five(ish) business days (through Tuesday, January 2) and until quorum (7) is reached.

**Comment by valencik** [comment]
We've hit quorum and the vote is approved, thanks folks.

Migration issue is here: https://github.com/typelevel/governance/issues/124
