### ISSUE TITLE
Project Submission: Doobie

### ISSUE THREAD

**Issue by jatcwang** [typelevel/governance#125]
### Project Name
Doobie

### Project Short Description
doobie is a pure functional JDBC layer for Scala

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [x] Organization Project
- [ ] Affiliate Project

### Project Management

Typelevel projects are required to have an appropriate Code of Conduct. The [Scala Code of Conduct](https://typelevel.org/code-of-conduct) is a good option, but not specifically required. Before submitting a project for inclusion, please ensure that a pointer to its Code of Conduct is clearly linked from its README, CODE_OF_CONDUCT.md, or website.

- [x] This project's Code of Conduct can be found at [README.md](https://github.com/tpolecat/doobie/blob/main/README.md)

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria). Please make sure that the project's license is on the approved list.

- [x] This project's license can be found at https://github.com/tpolecat/doobie/blob/main/LICENSE
### Additional Notes

Doobie is a library originally authored by @tpolecat, and now maintained by @jatcwang. It depends directly on typelevel libraries such as cats, cats-effect and fs2. 
We want to shift both the github repository and publishing to under org.typelevel

**Comment by valencik** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.

Voting open is open for five business days (through Friday, January 12th) and until quorum (7) is reached.

**Comment by valencik** [comment]
Really happy to see this submission. Doobie is a delightful project and a very important part of the ecosystem!

**Comment by tpolecat** [comment]
Endorse. Thanks @jatcwang for all your work on this.

**Comment by valencik** [comment]
That's quorum! Migration issue here: https://github.com/typelevel/governance/issues/126

Thanks folks!
