### ISSUE TITLE
Project Submission: perspective

### ISSUE THREAD

**Issue by Katrix** [typelevel/governance#132]
### Project Name
[perspective](https://github.com/Katrix/perspective)

### Project Short Description
Generic programming using higher kinded data and typeclasses. perspective provides tools for generic programming, and typeclasses for monad transformers and higher kinded data

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

### Project Management

All Typelevel projects follow the Typelevel Code of Conduct.
Organization projects do not need a `CODE_OF_CONDUCT.md` file, as the Typelevel GitHub Organization one will automatically apply.

<details><summary>Affiliate Project Instructions</summary>
<p>

Affiliate projects should copy the following template into a `CODE_OF_CONDUCT.md` file in their repo:

```
# Code of Conduct

Every member of our community has the right to have their identity respected. The Typelevel community is dedicated to providing a positive experience for everyone, regardless of age, gender identity and expression, sexual orientation, disability, neurodivergence, physical appearance, body size, ethnicity, nationality, race, or religion (or lack thereof), education, or socio-economic status.

Everyone is expected to follow the [Typelevel Code of Conduct] when discussing the project on the available communication channels.


## Moderation

If you have any questions, concerns, or moderation requests, please contact a member of the [Typelevel Code of Conduct Committee].

[Typelevel Code of Conduct]: https://typelevel.org/code-of-conduct
[Typelevel Code of Conduct Committee]: https://typelevel.org/code-of-conduct#contact
```

If you would like to be an additionally point of contact for Code of Conduct reports, you can include your contact information in the Moderation section like so:

```
## Moderation

If you have any questions, concerns, or moderation requests, please contact a member of the [Typelevel Code of Conduct Committee] or reach out to a project moderator:

- [Your Name Here](mailto:moderator@example.org)
```

In the event of a Code of Conduct report, affiliate projects should follow the instructions outlined in the [Enforcement Procedures Affiliate project processes][affiliate-processes] section.

</p>
</details>

- [x] I acknowledge that this project must follow the Typelevel Code of Conduct
- [x] As an affiliate project, the `CODE_OF_CONDUCT.md` file can be found at https://github.com/Katrix/perspective/blob/main/CODE_OF_CONDUCT.md

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria).
Please make sure that the project's license is on the approved list.

- [x] This project's license can be found at [LICENSE](https://github.com/Katrix/perspective/blob/main/LICENSE)

### Additional Notes
Parts of perspective are still under quite a bit of flux, but as I am expanding out to working on other stuff that also using perspective, it feels like a good sign that at least the core parts of perspective are ready for further use by more people.

While the is some overlap between perspective and cats-tagless and perspective and shapeless, I hope that does not become much of a problem, as perspective still does stuff slightly differently from how cats-tagless and shapeless do them.

[affiliate-processes]: https://github.com/typelevel/governance/blob/main/ENFORCEMENT-POLICY.md#affiliate-project-processes

**Comment by valencik** [comment]
Hi @Katrix,

Sorry for the delay.
Typelevel has [recently changed it's Code of Conduct](https://typelevel.org/blog/2024/03/11/code-of-conduct.html) and how we apply that Code of Conduct to affiliate projects.
We're still in the process of updating all our resources, like the issue template you've used here.

Once the new process is resolved and documented, I'll followup here.

**Comment by Katrix** [comment]
I saw that the issue template was update some time ago. Is there more that still needs to be updated, or can I update stuff and start the process?

**Comment by samspills** [comment]
Hey @Katrix, sorry for the delay!! Yes, if you could update to make those changes (I think really just switching to the new Typelevel code of conduct) then that is all that's needed and then we can call the vote <3

**Comment by Katrix** [comment]
Done, code of conduct has been updated

**Comment by valencik** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.

Voting open is open for five business days (through Monday, May 13th) and until quorum (7) is reached.

**Comment by valencik** [comment]
That's quorum! Migration issue here: https://github.com/typelevel/governance/issues/140

Thanks folks!
