### ISSUE TITLE
Remove old CODE_OF_CONDUCT.md files from org projects

### ISSUE THREAD

**Issue by valencik** [typelevel/governance#133]
It's much easy to control/update a central CODE_OF_CONDUCT.md file for the whole org.
So we're going to delete the adhoc CODE_OF_CONDUCT.md files from org projects so that they instead use the default one for the whole org.

Here's a search to find all the projects that manually specify a CODE_OF_CONDUCT.md file:

https://github.com/search?q=org%3Atypelevel+path%3ACODE_OF_CONDUCT.md&type=code

Edit: This is actually the better query, it filters out archived projects:

https://github.com/search?q=org%3Atypelevel+path%3ACODE_OF_CONDUCT.md+NOT+is%3Aarchived&type=code

**Comment by valencik** [comment]
All org projects now use the [Organization Code of Conduct defined in our .github repo](https://github.com/typelevel/.github/blob/0d9184cabf102aff719862f7adc0bcf0cb0db5cb/CODE_OF_CONDUCT.md)

**Comment by TonioGela** [comment]
@valencik given that now we're using/implying the default organization CoC in all the repos, does it make sense to have it explicitly in the giter8 template too [here](https://github.com/typelevel/typelevel.g8/blob/main/src/main/g8/CODE_OF_CONDUCT.md)?

**Comment by valencik** [comment]
> @valencik given that now we're using/implying the default organization CoC in all the repos, does it make sense to have it explicitly in the giter8 template too [here](https://github.com/typelevel/typelevel.g8/blob/main/src/main/g8/CODE_OF_CONDUCT.md)?

I'd rather keep it there, I don't think the most common usage of typelevel.g8 is creating a new org project. It should have sensible defaults for all usage.
