### ISSUE TITLE
Project Submission: Peloton

### ISSUE THREAD

**Issue by killaitis** [typelevel/governance#136]
### Project Name
[Peloton](https://github.com/killaitis/peloton)

### Project Short Description
An actor library for Cats Effect

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [X] Affiliate Project

### Project Management

All Typelevel projects follow the Typelevel Code of Conduct.
Organization projects do not need a `CODE_OF_CONDUCT.md` file, as the Typelevel GitHub Organization one will automatically apply.

<details><summary>Affiliate Project Instructions</summary>
<p>

Affiliate projects should copy the following template into a `CODE_OF_CONDUCT.md` file in their repo:

```
# Code of Conduct

Every member of our community has the right to have their identity respected. The Typelevel community is dedicated to providing a positive experience for everyone, regardless of age, gender identity and expression, sexual orientation, disability, neurodivergence, physical appearance, body size, ethnicity, nationality, race, or religion (or lack thereof), education, or socio-economic status.

Everyone is expected to follow the [Typelevel Code of Conduct] when discussing the project on the available communication channels.


## Moderation

If you have any questions, concerns, or moderation requests, please contact a member of the [Typelevel Code of Conduct Committee].

[Typelevel Code of Conduct]: https://typelevel.org/code-of-conduct
[Typelevel Code of Conduct Committee]: https://typelevel.org/code-of-conduct#contact
```

If you would like to be an additionally point of contact for Code of Conduct reports, you can include your contact information in the Moderation section like so:

```
## Moderation

If you have any questions, concerns, or moderation requests, please contact a member of the [Typelevel Code of Conduct Committee] or reach out to a project moderator:

- [Your Name Here](mailto:moderator@example.org)
```

In the event of a Code of Conduct report, affiliate projects should follow the instructions outlined in the [Enforcement Procedures Affiliate project processes][affiliate-processes] section.

</p>
</details>

- [X] I acknowledge that this project must follow the Typelevel Code of Conduct
- [X] As an affiliate project, the `CODE_OF_CONDUCT.md` file can be found at https://github.com/killaitis/peloton/blob/main/CODE_OF_CONDUCT.md

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria).
Please make sure that the project's license is on the approved list.

- [X] This project's license can be found at https://github.com/killaitis/peloton/blob/main/LICENSE

### Additional Notes

[affiliate-processes]: https://github.com/typelevel/governance/blob/main/ENFORCEMENT-POLICY.md#affiliate-project-processes

**Comment by valencik** [comment]
Quick note: I've edited your issue to add the repo link to the Project name.

Hi @killaitis, thanks for sharing your library! This looks quite cool. And good to see so much example code 🥰

**Comment by valencik** [comment]
The vote is confirmed!
Migration issue is here: https://github.com/typelevel/governance/issues/141

Thanks folks.
