### ISSUE TITLE
Project Submission: circe

### ISSUE THREAD

**Issue by hamnis** [typelevel/governance#142]
### Project Name
circe

### Project Short Description

circe is a JSON library for Scala.

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

### Project Management

All Typelevel projects follow the Typelevel Code of Conduct.
Organization projects do not need a `CODE_OF_CONDUCT.md` file, as the Typelevel GitHub Organization one will automatically apply.

<details><summary>Affiliate Project Instructions</summary>
<p>

Affiliate projects should copy the following template into a `CODE_OF_CONDUCT.md` file in their repo:

```
# Code of Conduct

Every member of our community has the right to have their identity respected. The Typelevel community is dedicated to providing a positive experience for everyone, regardless of age, gender identity and expression, sexual orientation, disability, neurodivergence, physical appearance, body size, ethnicity, nationality, race, or religion (or lack thereof), education, or socio-economic status.

Everyone is expected to follow the [Typelevel Code of Conduct] when discussing the project on the available communication channels.


## Moderation

If you have any questions, concerns, or moderation requests, please contact a member of the [Typelevel Code of Conduct Committee].

[Typelevel Code of Conduct]: https://typelevel.org/code-of-conduct
[Typelevel Code of Conduct Committee]: https://typelevel.org/code-of-conduct#contact
```

If you would like to be an additionally point of contact for Code of Conduct reports, you can include your contact information in the Moderation section like so:

```
## Moderation

If you have any questions, concerns, or moderation requests, please contact a member of the [Typelevel Code of Conduct Committee] or reach out to a project moderator:

- [Your Name Here](mailto:moderator@example.org)
```

In the event of a Code of Conduct report, affiliate projects should follow the instructions outlined in the [Enforcement Procedures Affiliate project processes][affiliate-processes] section.

</p>
</details>

- [x] I acknowledge that this project must follow the Typelevel Code of Conduct
- [x] As an affiliate project, the `CODE_OF_CONDUCT.md` file can be found [here](https://github.com/circe/circe/blob/series/0.14.x/CODE_OF_CONDUCT.md) 

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria).
Please make sure that the project's license is on the approved list.

- [x] This project's license can be found [here](https://github.com/circe/circe/blob/series/0.14.x/LICENSE)

### Additional Notes

[affiliate-processes]: https://github.com/typelevel/governance/blob/main/ENFORCEMENT-POLICY.md#affiliate-project-processes

**Comment by valencik** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.

Voting open is open for five business days (through Thursday, May 30th) and until quorum (7) is reached.

**Comment by valencik** [comment]
Yay! this is very exciting! 🎉 
A lot of folks thought circe was already an affiliate project. Glad to make it official!

**Comment by zmccoy** [comment]
Thanks for getting this in the door @hamnis

**Comment by valencik** [comment]
Vote confirmed, thanks folks!
Migration issue: https://github.com/typelevel/governance/issues/143
