### ISSUE TITLE
Project Submission: Catscript

### ISSUE THREAD

**Issue by Hombre-x** [typelevel/governance#149]
### Project Name
Catscript

### Project Short Description
Catscript is a newcomers-friendly and "stricter" version of fs2-io. The idea was born and got developed in the context of the latest GSoC and its components are, at the moment, part of [shellfish](https://github.com/davenverse/shellfish).
The TLDR is that for the most useful APIs of fs2-io returning `Stream[F, T]` Catscript will offer an API with the same signature but returning `IO[T]`, letting the newcomers totally skip the difficulty of mastering tagless final and streaming.
The library already features extensive documentation and some tutorials for newcomers.
The initial designers' idea was also to create a library that could have further simplified simple file handling operations to further lower the learning curve. The hope is to include this library in the [toolkit](https://github.com/typelevel/toolkit).

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [x] Organization Project
- [ ] Affiliate Project

### Project Management

All Typelevel projects follow the Typelevel Code of Conduct.
Organization projects do not need a `CODE_OF_CONDUCT.md` file, as the Typelevel GitHub Organization one will automatically apply.

<details><summary>Affiliate Project Instructions</summary>
<p>

Affiliate projects should copy the following template into a `CODE_OF_CONDUCT.md` file in their repo:

```
# Code of Conduct

Every member of our community has the right to have their identity respected. The Typelevel community is dedicated to providing a positive experience for everyone, regardless of age, gender identity and expression, sexual orientation, disability, neurodivergence, physical appearance, body size, ethnicity, nationality, race, or religion (or lack thereof), education, or socio-economic status.

Everyone is expected to follow the [Typelevel Code of Conduct] when discussing the project on the available communication channels.


## Moderation

If you have any questions, concerns, or moderation requests, please contact a member of the [Typelevel Code of Conduct Committee].

[Typelevel Code of Conduct]: https://typelevel.org/code-of-conduct
[Typelevel Code of Conduct Committee]: https://typelevel.org/code-of-conduct#contact
```

If you would like to be an additionally point of contact for Code of Conduct reports, you can include your contact information in the Moderation section like so:

```
## Moderation

If you have any questions, concerns, or moderation requests, please contact a member of the [Typelevel Code of Conduct Committee] or reach out to a project moderator:

- [Your Name Here](mailto:moderator@example.org)
```

In the event of a Code of Conduct report, affiliate projects should follow the instructions outlined in the [Enforcement Procedures Affiliate project processes][affiliate-processes] section.

</p>
</details>

- [x] I acknowledge that this project must follow the Typelevel Code of Conduct
- [ ] As an affiliate project, the `CODE_OF_CONDUCT.md` file can be found at 

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria).
Please make sure that the project's license is on the approved list.

- [ ] This project's license can be found at (project still needs to be created) 

### Additional Notes
As said, the project got developed as part of Shellfish, but since no original features of Shellfish were used, it makes sense to propose it as a standalone one. 
The parts that will compose this library live under [io/chrisdavenport/shellfish/FilesOs](https://github.com/davenverse/shellfish/blob/main/core/src/main/scala/io/chrisdavenport/shellfish/FilesOs.scala), while [docs](https://github.com/davenverse/shellfish/tree/main/docs) include the aforementioned extensive documentation.
No Shellfish Snapshots including all these features were published yet as there's still an ongoing issue with Maven Central publishing from the davenverse.
The mentors for this GSoC project were @TonioGela, @zetashift, @mpilquist and @lenguyenthanh

[affiliate-processes]: https://github.com/typelevel/governance/blob/main/ENFORCEMENT-POLICY.md#affiliate-project-processes

**Comment by valencik** [comment]
Hi @Hombre-x, terribly sorry for the delay, that's on me and not a reflection of your hard work here.

I appreciate the efforts to make newcomer friendly tools, and am exciting to see how this effort grows!

**Comment by valencik** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.

Voting open is open for five business days (through Thursday, September 12th) and until quorum (6) is reached.

**Comment by valencik** [comment]
Thanks folks, the vote is approved!

Migration issue is here: https://github.com/typelevel/governance/issues/150
