### ISSUE TITLE
Ownership of `typelevel-bot`

### ISSUE THREAD

**Issue by larsrh** [typelevel/governance#17]
I am still the de-facto owner of `typelevel-bot`, since its email address forwards to mine. Who wants to be owner? I would just change the forwarding, since the password of the account appears to be known at least to @rossabaker.

**Comment by rossabaker** [comment]
It would be good if that could forward to multiple people.  Singleton or multiple, I will join that set: ross@rossabaker.com.

**Comment by larsrh** [comment]
I've flipped the switch to forward the bot mail address to yours, Ross. You need to confirm that and it should be good to go.

Sadly, Google Domains does not allow multi-forward, but you can add some backup addresses in GitHub settings: https://github.com/settings/emails (those can also be used for password reset).
