### ISSUE TITLE
Ownership of YouTube channel

### ISSUE THREAD

**Issue by larsrh** [typelevel/governance#18]
Currently I am still the primary owner of the Typelevel YouTube channel. Other owners are @LukaJCB and @milessabin.

I suggest making @LukaJCB the primary owner, so I can withdraw from the account. But beforehand it would be nice to add some additional owners.

**Comment by milessabin** [comment]
Agreed, and I'd like to drop off as well.

**Comment by larsrh** [comment]
Any takers? We just need someone with a Google account.

**Comment by rossabaker** [comment]
I don't know how to YouTube, and I don't want to learn, but I will be an interim bus factor reducer.

**Comment by larsrh** [comment]
I've just removed @milessabin and invited @rossabaker. Ross, once you accept, you should be able to see account details here: https://myaccount.google.com/brandaccounts/. Once you confirm I will also remove myself.

**Comment by rossabaker** [comment]
I can't follow that link, but can confirm I appear as an owner with you and Luka.

**Comment by larsrh** [comment]
Link should work now :facepalm: there was an extra slash at the end ...

**Comment by larsrh** [comment]
Transfer complete :heavy_check_mark: Luca should now have full permissions and can add other people.
