### ISSUE TITLE
Domain management

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#19]
We've had a few recent requests for e-mail addresses (#17, https://github.com/orgs/typelevel/teams/maintainers/discussions/3).  Would it make sense to grant an active member access to that so we don't have to keep bothering @larsrh?  E-mail changes the most often, but hypothetically also host records, or making sure someone sees and pays the bill to renew the registration.

**Comment by larsrh** [comment]
`typelevel.org` and `scala-cats.org` are currently registered under my name on Google Domains. @ChristopherDavenport has full permissions to manage them, including modifying the DNS records and adding email aliases (which is dead simple). Auto-renewal is off and in the past I've done that manually, expensing it through OpenCollective. I'm happy to continue doing that and/or adding more people as admins.
