### ISSUE TITLE
Set up a Sonatype user for automated releases

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#23]
Create a Sonatype user for automated releases.  We could provide org-level secrets for this account, such that its blast radius would be Typelevel instead of all the other organizations those of us entering our credentials belong to.

* [x] provision an e-mail alias
* [x] set up a Sonatype account
* [x] get it Typelevel publish rights
* [x] add organization secrets
* [ ] remove per repo secrets

**Comment by armanbilge** [comment]
- [ ] remove all the per-repo secrets

**Comment by rossabaker** [comment]
@ChristopherDavenport, are you able to help with the e-mail address?  That will unblock some subsequent steps, which will unblock a bunch of @armanbilge's builds.

**Comment by rossabaker** [comment]
Progress: https://issues.sonatype.org/browse/OSSRH-78632

**Comment by armanbilge** [comment]
Hooray, thanks for chasing down the email stuff!

> Please grant @typelevel-bot publish access to typelevel.org on s01.

Your comment there is a bit vague; orgs can't be half-and-half publishing to the legacy host and s01. So if we're asking for migration (we can!) we should ask for that :)

**Comment by rossabaker** [comment]
I picked s01 in a dropdown, but I continue to be befuddled by what breaks and doesn't in this migration.  If you know specifically what to ask for, I'll go endorse your comment.

**Comment by armanbilge** [comment]
Right, because of the breakage I thought this might want to run by a committee vote first. But if we're go, we're go.

**Comment by rossabaker** [comment]
What happens precisely?  Everyone has to change their host in their builds, which many projects would get free with sbt-typelevel changing its default?  I thought there was agreement the one we've been using is decaying.  We can post an announcement to the maintainers.

**Comment by armanbilge** [comment]
> Everyone has to change their host in their builds

Yes and anyone publishing with Sonatype "tokens" (these are the generated username/password) will also break and need to be re-generated on s01:

> Also, keep in mind that if you are using Tokens instead of username/credentials to publish you will need to generate new tokens and replace those in your current setup from here

See https://github.com/http4s/sbt-http4s-org/pull/135#issuecomment-1032186185

> which many projects would get free with sbt-typelevel changing its default?

Yes, in fact we don't even need to change the default and cut a release: we can now set a `SONATYPE_CREDENTIAL_HOST` org-wide secret to change this immediately.

I think the bulk of projects are on sbt-typelevel according to https://github.com/typelevel/sbt-typelevel/issues/83.

> I thought there was agreement the one we've been using is decaying.

The original ticket was on the defunct typelevel/general in https://github.com/typelevel/sbt-typelevel/issues/84. Consensus would probably be you and (implicitly) Rob 😆

**Comment by rossabaker** [comment]
Let's move forward.  This has languished for months, and the new shared account is our chance to do it right.

**Comment by armanbilge** [comment]
I updated them on the sonatype jira.

**Comment by armanbilge** [comment]
Update: our bot now has publish rights and `org.typelevel` has been migrated to s01!

https://issues.sonatype.org/browse/OSSRH-78632?focusedCommentId=1146426&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1146426

Next:
1. Obtain credentials for the Typelevel Release Bot. If they are generated tokens (probably best) they should be generated at https://s01.oss.sonatype.org/
2. Install credential as org-level secrets `SONATYPE_USERNAME` and `SONATYPE_PASSWORD`
3. Set org-level secret `SONATYPE_CREDENTIAL_HOST` to `s01.oss.sonatype.org`

After 1,2,3 we can make an announcement to maintainers. All secrets should be removed from individual repositories, including `PGP_SECRET` and `PGP_PASSPHRASE`.

**Comment by rossabaker** [comment]
1. Done, with token
2. Done
3. Done

**Comment by armanbilge** [comment]
Thanks, let me test it with an sbt-typelevel snapshot.

**Comment by armanbilge** [comment]
sbt-typelevel snapshot successfully published to s01 :)
https://s01.oss.sonatype.org/content/repositories/snapshots/org/typelevel/

I will make an announcement to maintainers.

**Comment by armanbilge** [comment]
Various repos are pinging me about publication failures. Most maintainers don't have the necessary rights to fix this themselves.

If an admin wants to make the rounds and delete the per-repo secrets for all the sbt-typelevel adopters listed in https://github.com/typelevel/sbt-typelevel/issues/83 I'd be much obliged :)

**Comment by rossabaker** [comment]
I cleaned these up today:

* case-insensitive
* cats-uri
* frameless
* jawn
* jawn-fs2
* keypool
* log4cats
* monoids
* scalacheck-effect
* vault

There is another set of projects that I _suspect_ are broken, but I'm not involved with enough to feel confident modifying them.  I'll add those to the maintainers discussion for greater visibility.

**Comment by armanbilge** [comment]
I reckon we can close this one; the issue headline is done anyway. I'm sure there's a handful of stragglers but nothing we can't handle as they reveal themselves.
