### ISSUE TITLE
Name the first Chair

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#24]
[Section 2.2 of the charter](https://github.com/typelevel/governance/blob/f94465c436b1e4dd9bf83cb2a4aefc0844fafdb8/CHARTER.md#2-steering-committee) says:

> The Steering Committee will appoint a Chair responsible for organizing Steering Committee activity.

The only enumerated responsibility is:

> The Steering Committee Chair will call a vote with reasonable notice to the Steering Committee, setting out a discussion period and a separate voting period.

**Comment by rossabaker** [comment]
Many issues are stuck, and nobody was empowered to call a vote before we launched the charter.  I propose we hold this open for 72 hours for volunteers to serve as the first chair, and then call a vote.

**Comment by rossabaker** [comment]
I volunteer to serve on an interim basis.  My proposed agenda:

* Post a public call for new members
* Identify and implement a voting system
* Call for votes on deadlocked issues
* Initiate a process to choose officers for a first regular term

**Comment by johnynek** [comment]
Hear hear!

**Comment by rossabaker** [comment]
It's been 72 hours.  I'll submit myself to emojocracy. and I promise zero hard feelings on a thumbs down.  5 votes is a quorum, 5 affirmative votes clinches it.

/cc @typelevel/steering

**Comment by ChristopherDavenport** [comment]
After a significant delay and nay votes, I believe we have consensus/a quorum to acknowledge Ross as chair.

Thank you for stepping up to this critical role!

**Comment by johnynek** [comment]
🎉
