### ISSUE TITLE
Domain administrators

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#30]
We have several initiatives (#21, #22, #23, #29) blocked not having admin access on the domain, specifically to set up e-mail aliases.  We thought @ChristopherDavenport had access, but Chris does not see it on his end.  We may need another favor from @larsrh.

It would be great to have two active admins.  I volunteer to be the backup, but I don't know how Google domains work.

**Comment by larsrh** [comment]
@ChristopherDavenport Could you try accessing https://domains.google.com/registrar/typelevel.org/email? It should let you define aliases in case you are logged in with your address ending in `christopherdavenport.tech`.

@rossabaker Happy to add you as well, I just need an email address that's associated with a Gmail account.

**Comment by rossabaker** [comment]
Thanks, Lars!  I'm `rossabaker@gmail.com`.  Not my primary contact, but is mine, is monitored, and is Gmail.

**Comment by larsrh** [comment]
Just added you there.

**Comment by rossabaker** [comment]
Thanks, I confirmed it works, and I can see Chris.

We still need to figure out how to forward to multiple people, but this gets us unblocked and lets us let you enjoy retirement.
