### ISSUE TITLE
Sharing passwords for shared accounts

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#32]
We have a small handful of shared accounts and no way to share the password to reduce the bus factor.

* typelevel-bot on Sonatype has an e-mail that goes to the steering committee.  Presumably we could force a reset there.
* The typelevel-bot GitHub is tribal knowledge
* I don't know who has the Twitter.  I'm on a Tweetdeck team with limited access.

**Comment by rossabaker** [comment]
Reminder: the steering committee has access to [this list of assets](https://docs.google.com/document/d/1CouLq_zRyTrXpHfrHzpUHo38IpjD2fbRWIV7mhhsFqw/edit#).  I haven't made it public out of opsec paranoia, but maybe it's more likely we all lose access to that than an adversary uses it as a treasure map from this repo.

**Comment by armanbilge** [comment]
A private GH repo seems better than a google doc? Although FYI activity in the governance repo leaked on the Discord #typelevel-github channel even while it was private.

**Comment by rossabaker** [comment]
That's a great idea.  I somehow forgot we had that capacity, even though I've set up more than one in this org.  I will migrate that asset document there.

It's still not a password manager, and I like @djspiewak's idea.

**Comment by djspiewak** [comment]
Oh that's definitely bothersome. I think the token which is doing the notifications has access to a lot of things.

**Comment by Daenyth** [comment]
What about bitwarden? It has options for cloud hosting and self-hosting, and it's open source

**Comment by rossabaker** [comment]
I have sent out a poll to @typelevel/steering using [CIVS](https://civs1.civs.us/).  If anyone did not get a ballot, please ping me.  I will post the results in a week.

**Comment by rossabaker** [comment]
Oops.  Everyone needs to [opt in](https://civs1.civs.us/cgi-bin/opt_in.pl) with their e-mail address (same as you were invited to the typelevel-steering mailing list) to receive their ballot.

**Comment by rossabaker** [comment]
I might have been wrong in the description: I said the ballots would be private, but it's telling me when I vote that it's not.  Sorry I missed a checkbox, but I don't think this is particularly delicate.  I'm just trying to get a decision made.

**Comment by rossabaker** [comment]
Only three people voted, which is short of a quorum.

```
1. git-secret  (Not defeated in any contest vs. another choice)
--
2. Tied:
   1Password, loses to git-secret by 2–1
   Keeper
   Bitwarden
5. manual gpg, loses to 1Password by 2–0
```

git-secret "won" and is the shortest path from here.  All we need is GPG public keys for anyone who should have the secrets.

**Comment by alexandru** [comment]
Hey — I'm not part of any current discussions, sorry about dropping in with an opinion on this one ...

I've had bad experiences with `git-secret` and similar solutions. Anything based on git or GPG for keeping shared secrets is a terrible solution.

Out of that list, the only 2 solutions worth speaking of are 1Password and Bitwarden. I would go for 1Password because it's the only one I've experienced that doesn't suck, but Bitwarden isn't terrible either, the only problem is that it's going to cost money.

Also, you can setup an 1Password for Teams account and it's should be free for Open Source projects:

**Comment by rossabaker** [comment]
I need to invite at least one other owner to apply for the open source license.  I need a preferred e-mail address for anyone who wants to join.  I created a Typelevel e-mail alias for myself, to keep this account separate from my personal 1Password use, and can also do the same for you.

**Comment by djspiewak** [comment]
`djspiewak@gmail.com`

`27DD C030 0B8C 55E0 FF6A  14E8 4663 0499 1E23 B3D7`

**Comment by rossabaker** [comment]
I have applied for the 1Password Open Source Team and added Daniel.  If that gets accepted, we can close this.  If not, I'll pursue the git-secret.

**Comment by ChristopherDavenport** [comment]
chris@christopherdavenport.tech for an email.

**Comment by rossabaker** [comment]
They approved the account, and I've moved in the secrets that I have.  Someone please close once they confirm access to the shared vault.
