### ISSUE TITLE
Old Typelevel mailing list

### ISSUE THREAD

**Issue by larsrh** [typelevel/governance#33]
The old Typelevel mailing list is still around: https://groups.google.com/g/typelevel/

The most recent post is from 2017, so I think it is safe to declare it 'defunct'. What should happen to it? Delete it? Remove all users & close it for posting?

**Comment by rossabaker** [comment]
> Remove all users & close it for posting?

I think you can just restrict posting to admins and not have to click through to chase everyone off.  Otherwise, this.

**Comment by larsrh** [comment]
Found the setting, done.
