### ISSUE TITLE
Enable Github Two-Factor Requirement

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/governance#35]
As of this moment this is not a requirement to be a member of the org.

It is put forward for consideration that this should be enabled to help guarantee that Typelevel organization members are secure in their interaction with code.

A note that if enabled will silent kick anyone who does not have it enabled.

> Members, billing managers, and outside collaborators who do not have two-factor authentication enabled for their personal account will be removed from the organization and will receive an email notifying them about the change.

**Comment by rossabaker** [comment]
Yes, but it would be good to have a grace period.  This currently applies to nine humans, at least a few of which are highly active.

It also applies to @typelevel-bot.  We can work around that, but it will tie into #32.

**Comment by rossabaker** [comment]
If this is a hardship for anyone, please speak up here or reach out privately, and we can seek a solution that's both inclusive and secure.

/cc @typelevel/maintainers

**Comment by rossabaker** [comment]
Howto: https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa

I just sent an e-mail or tweet to everyone outstanding.

I also added 2FA to @typelevel-bot.  Contact me for the TOTP secret.

**Comment by rossabaker** [comment]
Everyone has been contacted.  Most responded, one opted out, and everyone has been told they're welcome back.  I say it's safe to flip the switch.

**Comment by rossabaker** [comment]
Done.  If anyone wants back in, please contact an admin.
