### ISSUE TITLE
typelevel.g8

### ISSUE THREAD

**Issue by valencik** [typelevel/governance#39]
I would like to propose and offer [proto-typelevel.g8](https://github.com/valencik/proto-typelevel.g8/) as a typelevel project.

- Provides a [giter8](http://www.foundweekends.org/giter8/) template to help with library creation using typelevel [sbt-typelevel](https://github.com/typelevel/sbt-typelevel) and other best practices
- This work was spawned out of https://github.com/typelevel/sbt-typelevel/issues/37
- Additionally, this serves as a minimal example of how to use sbt-typelevel, creating all necessary files and pieces to leverage its features.
- Chosen defaults: Scala 2.13 and 3.1 on JVM and JS
- Comes with reasonable CI testing for hopefully easy maintenance

You can test it out in it's current form via:
```sh
sbt new valencik/proto-typelevel.g8
```

### Recognition

Special thanks to @armanbilge and @rossabaker for their help.
And further thanks to contributors of similar and previous works such as https://github.com/davenverse/library.g8 and https://github.com/typelevel/sbt-catalysts.g8

If accepted, I will need some help to transfer the repo into the Typelevel org.

**Comment by rossabaker** [comment]
Thanks for starting this.  I tried it this afternoon and like it, and it's a natural pair for sbt-typelevel.

**Comment by rossabaker** [comment]
@typelevel/steering: vote on the original post with :+1: or :-1:.  Let's give it a week so everyone has a chance.

**Comment by rossabaker** [comment]
That's a quorum.  The project is accepted.

@valencik, if you transfer it to the Typelevel GitHub org, I'll keep an eye out for the request and set up permissions.

**Comment by valencik** [comment]
Thanks @rossabaker, happy to hear it.

Unfortunately I cannot transfer ownership to Typelevel as I don't have permissions to create repositories within the org. When trying I run into the following error:

> You don’t have the permission to create public repositories on typelevel 

I wonder if I can add you as an owner and then you could do the transfer?

**Comment by valencik** [comment]
Ahh, nevermind, we're up and running now :)
https://github.com/typelevel/proto-typelevel.g8
