### ISSUE TITLE
Propose sbt-tpolecat as a Typelevel project

### ISSUE THREAD

**Issue by DavidGregory084** [typelevel/governance#41]
I would like to propose [sbt-tpolecat](https://github.com/DavidGregory084/sbt-tpolecat) as a Typelevel project.

It's an sbt plugin that is used for setting scala compiler options in order to get the greatest benefit out of the compiler's linting features, originally inspired by @tpolecat's blog posts on the topic. It currently supports Scala 2.11 - 3.1 for sbt 1.x only.

The repo is set up for auto-publishing using sbt-ci-release and generally requires little maintenance. Recently there has been a little more activity as some more features have been added to the plugin to set different scalac option modes.

I hope that it will be useful as part of sbt-typelevel as proposed in typelevel/sbt-typelevel#256.

If accepted, I will need your advice and assistance to transfer the repo into the Typelevel org.

**Comment by rossabaker** [comment]
:tada: I've used and appreciated this project for a long time.  

To be clear, are you proposing it as a full Typelevel project (i.e., transferred into our GitHub org), or an affiliate project (keep it where it is)?

**Comment by DavidGregory084** [comment]
I'd like to propose it as a full Typelevel project if it is suitable 😀

**Comment by rossabaker** [comment]
@typelevel/steering: :+1: on the original comment to approve sbt-tpolecat as a Typelevel project, :-1: to reject, :eyes: to be present.  Vote will close after 72 hours and quorum is reached.

**Comment by rossabaker** [comment]
Approved: 7 yes votes is > 3/4 even if everyone else says no.  

@DavidGregory084, I think if you initiate a GitHub transfer, one of us will see the request and be able to complete it.

Do we need a separate team from sbt-typelevel / typelevel.g8, or say they're closely enough related to be one team?  I lean toward the latter.

**Comment by armanbilge** [comment]
Yes, I was hoping this might join the sbt-typelevel team :) mostly so I can poach @DavidGregory084 who's becoming a regular and valuable sbt-typelevel contributor 😉

**Comment by DavidGregory084** [comment]
OK, I had a go at initiating the transfer but it looks like I may need to be a team member first?

<img width="515" alt="image" src="https://user-images.githubusercontent.com/2992938/165183834-470eda66-fd4a-44e8-8707-13ddd4ca876a.png">

**Comment by rossabaker** [comment]
Oh, shoot.  I relearn this every time.  Please accept the org (and team) invite, and try again.  Once it's transferred, an admin can add the repo to the team.

**Comment by DavidGregory084** [comment]
That seems to have worked 🎉
