### ISSUE TITLE
New project: otel4s

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#43]
I would like to offer [otel4s](https://github.com/rossabaker/otel4s) as a Typelevel project.  It is an Open Telemetry library built on Cats-Effect.  Rough plans:

* a platform neutral core based on the standard Otel API
* an opentelemetry-java backend to bootstrap JVM usage
* the possibility of a Scala.js backend
* the possibility of a pure Scala backend

**Comment by ChristopherDavenport** [comment]
Definitely think this is a great idea.

**Comment by rossabaker** [comment]
Let's vote through Monday, June 6.
* Quorum is 7.  
* 9 yeas clinches it.
* :+1: or :-1: on the original

/cc @typelevel/steering

**Comment by rossabaker** [comment]
It's approved.  I'll work on the logistics of it tomorrow.
