### ISSUE TITLE
Create template for new project submissions

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#57]
Something we can link from the website to lower the friction.

**Comment by valencik** [comment]
How do you feel about a GitHub issue template for this?

I'm thinking the following fields as required:

- Project Name (GitHub repo name)
- Project Short Description (for GitHub repo description)
- Organization Project or Affiliate Project?

And then we could have an optional section with a longer description / jot notes.
This would mostly match the last couple proposals: 

We could also auto tag with `projects` label and perhaps the `vote` label

**Comment by rossabaker** [comment]
That sounds perfect.

**Comment by valencik** [comment]
I think we can call this complete as of https://github.com/typelevel/governance/pull/66
