### ISSUE TITLE
Domain handover

### ISSUE THREAD

**Issue by larsrh** [typelevel/governance#62]
(Follow-up to #19. I would like to do a handover now since it seems like Typelevel governance is in good hands now, and there is more action regarding website reboot etc.)

As far as I can tell, the last remnants of my Typelevel patronage are the domains:

* `typelevel.org`
* `scala-cats.org`

The domains are currently hosted at Google Domains. This is fairly stable and required no intervention from my side in a long time.

Current co-owners of the domain are:

* @rossabaker 
* @ChristopherDavenport 

Similarly, both domains are registered in the Google Search Console to track search performance.

I suggest the following course of action:

* [x] Change the owner address of the domains (currently, they are both set to my private residence, albeit protected through WHOIS anonymization)
* [x] Add more co-owners to the domain
* [x] Remove my ownership at Google Domains, this can be done here:
  * https://domains.google.com/registrar/scala-cats.org/settings
  * https://domains.google.com/registrar/typelevel.org/settings
* [x] Enable auto-renew for those domains (currently, they are set to expire end of 2023, so there's sufficiently much headway)

**Comment by jducoeur** [comment]
I'm fine with being added as a co-owner.

**Comment by rossabaker** [comment]
I like Lars' plan, and converted it to a checklist.  I can remove Lars once the change of address is approved.

**Comment by larsrh** [comment]
I clicked on an approval link that Google sent me, but I think @rossabaker also has to click on approve?

**Comment by rossabaker** [comment]
I set up my payment method for the auto-renew.  Whenever I get billed, I'll pass it on to the Collective.

**Comment by larsrh** [comment]
Thanks!
