### ISSUE TITLE
New member github permissions

### ISSUE THREAD

**Issue by samspills** [typelevel/governance#63]
It looks like new steering committee members don't have permissive-enough github permissions. 

ex. I can't create new teams within the maintainers group. 

This issue stems from a discord discussion with @ChristopherDavenport, [convo starts here](https://discord.com/channels/632277896739946517/839550585992904734/1014156909584076840)

**Comment by samspills** [comment]
Chatted a bit more with Chris and it sounds like one sure fire way to grant the appropriate permissions is to make us all `owners` but that's perhaps too broad of a permissions brush? 

What do other @typelevel/steering folks think?

**Comment by jducoeur** [comment]
I'm okay with all members of the steering committee having the owner bit turned on -- sort of goes with the territory -- but it's the usual tension between security and convenience.  The alternative is probably that some members of the committee have the bit, and also have the responsibility to deal with this sort of thing.

**Comment by rossabaker** [comment]
I agree with @jducoeur.  I trust everyone individually, but there's good reason not to turn it on unless people are exercising it.

Sounds like maybe the current set isn't enough, and @samspills tried to help.  I'd propose we add her for now, if she wants it.

**Comment by samspills** [comment]
Yes please @rossabaker, I would like to be added! I can help with some management/admin/glue work type tasks :)

**Comment by rossabaker** [comment]
Done.  If anyone else needs it or wants to shed it, ping an owner.
