### ISSUE TITLE
Project submission: Fabric JSON Library

### ISSUE THREAD

**Issue by darkfrog26** [typelevel/governance#65]
I've written a very fast and reliable JSON library that I'd like to be subsumed under Typelevel if it meets the proper criteria: https://github.com/outr/fabric

It is arguably the fastest JSON library in Scala and offers immutable internal types as opposed to uPickle and is far easier to use than Circe. It is published for JVM, JS, and Native with 2.13 and 3 support.

**Comment by mpilquist** [comment]
Excited to see this & looking forward to taking a look!

**Comment by darkfrog26** [comment]
@mpilquist thanks! I've got a few projects I'd like to potentially consider bringing over, just testing the waters with this one. Let me know if there's anything I can do or provide to help you all out.

**Comment by jducoeur** [comment]
Just to make sure we're all on the same page -- are you looking for this to be an "Organization" project (managed by TL), or an "Affiliate" project (associated with TL)?  Definitions can be found in [the Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md).

**Comment by darkfrog26** [comment]
@jducoeur thanks for clarifying, I'm looking for it to be an "Organization" project.

**Comment by rossabaker** [comment]
@typelevel/steering, you know the drill: :+1: to approve, :-1: to reject, :eyes: to count toward quorum.  We'll close it Monday if there's a quorum, or earlier if the outcome is clinched.

**Comment by rossabaker** [comment]
There's already an http4s-fabric module.  I also like seeing new approaches with different tradeoffs.  I think it's a neat project, and I'm in favor.

**Comment by rossabaker** [comment]
The vote passes with a quorum (9/13 > 50%) and at least a three-quarters vote (unanimous).

I created a fabric team and added @darkfrog26 as the admin.  When the repo gets transferred, we'll need to assign it to that team.  And we can add the project [here](https://github.com/typelevel/typelevel.github.com/tree/development/collections/_projects) to get it on the website.

**Comment by darkfrog26** [comment]
Just to be clear, the next step for me is to transfer the repository to `typelevel`?

**Comment by darkfrog26** [comment]
@rossabaker I'm ready to migrate `fabric` but need confirmation about the repository I'm moving to. :)

**Comment by valencik** [comment]
:wave: hi @darkfrog26, yes, transfer ownership to the [typelevel](https://github.com/typelevel) organization.

I believe you should now have permissions to create repos under typelevel and can therefore complete the transfer.

**Comment by darkfrog26** [comment]
@valencik thanks! The transfer is complete. Is there a checklist of next steps?

**Comment by valencik** [comment]
I don't know if we have a checklist, we likely should.
Just some thoughts on what we could do next:

- [ ] Add fabric to the [site by opening a PR here](https://github.com/typelevel/typelevel.github.com/tree/development/collections/_projects)
- [ ] Write a blog post announcing the change
- [ ] Tweet about it

@darkfrog26 Would you be interesting in writing up a brief blog post that perhaps introduces fabric a bit?

**Comment by samspills** [comment]
Yes, a checklist would be great!

We could/should capture earlier steps as well:
- [ ] create a team for the repo with maintainer as team member
- [ ] after repo transfer, add repo with `write` permissions to the created team 

Ross already handled the team creation and I just added the repo to the team perms, so I think in terms of github org management we're done??

**Comment by darkfrog26** [comment]
Is there any documentation on doing releases and switching to the SBT plugin for Typelevel?

**Comment by darkfrog26** [comment]
Do I just submit a PR here to submit a blog post? https://github.com/typelevel/typelevel.github.com/tree/development/collections/_posts

**Comment by armanbilge** [comment]
> Is there any documentation on doing releases and switching to the SBT plugin for Typelevel?

https://typelevel.org/sbt-typelevel/

**Comment by valencik** [comment]
Closing as completed :)

The remaining announcement endeavors we can followup on in https://github.com/typelevel/governance/issues/67
