### ISSUE TITLE
Migrating: Fabric

### ISSUE THREAD

**Issue by valencik** [typelevel/governance#67]
## Migration Checklist

Project Submission Issue: https://github.com/typelevel/governance/issues/65

### For Organization Projects:

- [x] Create a team for the repo with maintainer as team member
- [x] After repo transfer, add repo with write permissions to the created team

### For All Projects:

- [x] Add project to the site by [adding a file here](https://github.com/typelevel/typelevel.github.com/tree/development/collections/_projects)

### Announcements

These steps are optional but encouraged.

- [x] Write a blog post announcing the change
- [x] Post to our social channels (Twitter, Mastodon)

**Comment by valencik** [comment]
Hey @darkfrog26

Just noticed this from the previous issue:

> Do I just submit a PR here to submit a blog post? https://github.com/typelevel/typelevel.github.com/tree/development/collections/_posts

Yes, that is we're you'd add a blog post to. :)

**Comment by darkfrog26** [comment]
Can someone tell me why this is erroring? It's very confused about the Macros for Scala 2 and incorrectly failing the build as a result: https://github.com/typelevel/fabric/actions/runs/3420665742/jobs/5695778192

**Comment by darkfrog26** [comment]
Sorry it took so long, but here's the blog post PR: https://github.com/typelevel/typelevel.github.com/pull/406

**Comment by darkfrog26** [comment]
I *think* we can mark this as done.

**Comment by rossabaker** [comment]
I'm off Twitter, but gave it a belated toot just now.
