### ISSUE TITLE
Project Submission: fs2-data

### ISSUE THREAD

**Issue by satabin** [typelevel/governance#68]
### Project Name
[fs2-data](https://github.com/gnieh/fs2-data)

### Project Short Description
fs2-data is a library of streaming parsers and transformations for various semi structured data format (including CSV, JSON, XML, and CBOR). It also comes with support for query languages for these formats (e.g. XPath and JSONPath), and the possibility to define new ones.

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [X] Affiliate Project

**Comment by satabin** [comment]
Maintainers are @ybasket and @satabin

**Comment by valencik** [comment]
Updated issue to link to https://github.com/gnieh/fs2-data

**Comment by valencik** [comment]
@typelevel/steering :wave: 

Let's vote!
:+1:  to approve, :-1:  to reject, :eyes:  to count toward quorum

We can close it next Monday, November 21st, if there's a quorum

**Comment by samspills** [comment]
Big fan of fs2-data ❤️❤️

**Comment by valencik** [comment]
Sorry for the delay.

Thanks voters, we've hit a quorum.
And thank you fs2-data maintainers!
It's approved! 🎉 

fs2-data has been accepted as an affiliate project of Typelevel.
Tracking the remaining tasks here: https://github.com/typelevel/governance/issues/69

**Comment by satabin** [comment]
Thanks @valencik! No worries for the delay. I am super happy fs2-data was accepted.

For the remaining steps, should I open a PR or are Typelevel members taking care of it?

**Comment by jducoeur** [comment]
PRs are welcome, if you'd like to do so -- that would save us some effort and speed things up.

I'd say the most useful thing would be if you could draft a short introductory overview of fs2-data for those who don't know it, either as [a PR for the blog post](https://github.com/typelevel/typelevel.github.com/tree/development/collections/_posts) or just a comment here.
