### ISSUE TITLE
Migrating: fs2-data

### ISSUE THREAD

**Issue by valencik** [typelevel/governance#69]
## Migration Checklist

Project Submission Issue: https://github.com/typelevel/governance/issues/68

### For Organization Projects:

- ~~[ ] Create a team for the repo with maintainer as team member~~
- ~~[ ] After repo transfer, add repo with write permissions to the created team~~

### For All Projects:

- [x] Add project to the site by [adding a file here](https://github.com/typelevel/typelevel.github.com/tree/development/collections/_projects)

### Announcements

These steps are optional but encouraged.

- [ ] Write a blog post announcing the change
- [x] Post to our social channels (Twitter, Mastodon)

**Comment by rossabaker** [comment]
It has been tooted.

**Comment by valencik** [comment]
Closing as the required basics are done. A blog post is optional and come later if desired.
