### ISSUE TITLE
Project Submission: `parsley-cats`

### ISSUE THREAD

**Issue by j-mie6** [typelevel/governance#70]
### Project Name
[parsley-cats](https://github.com/j-mie6/parsley-cats)

### Project Short Description
The `parsley-cats` library exposes `cats` instances for `MonoidK[Parsley]`, `Monad[Parsley]`, and `FunctorFilter[Parsley]` for the `org.github.j-mie6/parsley` parsing library.

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

**Comment by rossabaker** [comment]
@typelevel/steering Let's see if we can get a quorum by Friday.  :+1: to approve, :-1: to reject, :eyes: to be present.

**Comment by rossabaker** [comment]
I'm strongly in favor.  I have enjoyed Parsley in both Scala and Haskell, and a Cats integration is obviously germane to Typelevel.  Even though we have Cats-Parse in house, we've always welcomed differing approaches in the same domain.  I'm glad to see this.

**Comment by rossabaker** [comment]
The momentum is clear, but the quorum is a high bar around the holidays.  Needs three more if anyone's online.  /cc @typelevel/steering.

**Comment by rossabaker** [comment]
There's our quorum.  Vote passes, 9-0.  The linked ticket should get it added to our website.

**Comment by j-mie6** [comment]
Do I get a shiny new GitHub badge now? 😁

**Comment by rossabaker** [comment]
https://typelevel.org/cats/img/cats-badge.svg :smile:

**Comment by j-mie6** [comment]
Should/can I add the typelevel: affiliate badge to the repo, or no?

**Comment by rossabaker** [comment]
There's no requirement or standard, but I think it's something we should offer.  I'm proposing a standard at #72.
