### ISSUE TITLE
"Blank issue" template

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#71]
It took me almost a minute to find out how to open an issue that doesn't match our templates.  The templates are great.  The GitHub UI is not.  Maybe there should be a blank issue template so it's as obvious as the others.

Hit new issue and see for yourself, and feel free to close if I'm being grumpy.

**Comment by jducoeur** [comment]
Ah -- yeah, I can guess why they do it that way, but it's weirdly unobvious.  Having a blank template might be a good idea.

**Comment by zmccoy** [comment]
Yeah, a "Other" or something like it would be good to have.
