### ISSUE TITLE
Team Discussions are Sunsetting

### ISSUE THREAD

**Issue by valencik** [typelevel/governance#80]
The GitHub "Team Discussions" feature is being deprecated.
https://github.blog/changelog/2023-02-08-sunset-notice-team-discussions/

We have used a the `maintainers` team discussion board.
https://github.com/orgs/typelevel/teams/maintainers

The recommended action to use change our Team discussions into Organization Discussions.
So instead of being at the team level, they'll be at the org level.

![image](https://user-images.githubusercontent.com/5440389/218093904-3b45fc05-18e8-4ecd-ae95-0276829967e1.png)

Edit: I've just checked all the other teams, no discussions, so it's just the `maintainers` team discussion that we'd need to migrate.

**Comment by jducoeur** [comment]
Given that that discussion was fairly broadly scoped, I don't see any obvious security concerns.  So this looks straightforward.

**Comment by rossabaker** [comment]
If I understand correctly:
* transferring to a private repository would restrict it to members of the org (roughly coterminous with "maintainers," but @jducoeur slipped through the cracks)
* transferring to a public repository would let anybody see (but maybe or maybe not take part?)
* not transferring would leave the extant ones read-only, but we'll still want to pick one of the above moving forward?

**Comment by rossabaker** [comment]
I don't think any of the prior maintainer discussions have been "classified documents," and if they were, I don't know that GitHub would be the ideal way to broadcast it.  Moving forward, regardless of whether we transfer the old ones or not, the public option sounds right.

**Comment by jducoeur** [comment]
We should make sure that everyone understands that it's public, but agreed.

**Comment by rossabaker** [comment]
Well, we missed the deadline, but there's a JSON archive on the team page that told me what I needed to know.

To enable the org discussions, we need to pick a repository.  This one seems as good as any.

**Comment by samspills** [comment]
Agreed, this repo makes sense for discussions

**Comment by rossabaker** [comment]
Done: https://github.com/orgs/typelevel/discussions
