### ISSUE TITLE
Project submission: endless4s

### ISSUE THREAD

**Issue by jchapuis** [typelevel/governance#82]
Would it be possible to add https://endless4s.github.io/ to the list of projects?

"Sharded and event-sourced entities for Cats Effect"

Thanks!

**Comment by jducoeur** [comment]
I'd love to see that, personally -- as a very-long-time Akka Cluster Sharding user, I've had my eye on endless4s for a while.  The abstractions are really interesting.

To apply, [add an issue using this template](https://github.com/typelevel/governance/blob/main/.github/ISSUE_TEMPLATE/1-project-submission.md).

**Comment by samspills** [comment]
closing this in favour of #89 :)
