### ISSUE TITLE
Project Submission: Lepus

### ISSUE THREAD

**Issue by hnaderi** [typelevel/governance#83]
### Project Name
[Lepus](https://github.com/hnaderi/lepus)

### Project Short Description
Purely functional, non-blocking RabbitMQ client for scala, scala js and scala native built on top of fs2

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

**Comment by rossabaker** [comment]
Looks like a good fit.  Also, the *.org warms my heart.

One question: is there a Code of Conduct for the project?

**Comment by hnaderi** [comment]
> One question: is there a Code of Conduct for the project?

No, there was no explicit code of conduct in the project; but I added one now, Also if there are some criteria it needs to have, let me know.


> Also, the *.org warms my heart.

I'm completely OK with an org project too, if it might be a good fit.

**Comment by rossabaker** [comment]
Oh, I was referring to the Org Mode docs. :smile:

Organization vs. affiliate project application is up to you.  If in doubt, affiliate is easy and low risk: you don't have to move it now, can keep building interest in it, and can always reapply as an org project later.  I'll call a vote of the Steering Committee here once you confirm which direction you'd like to go.

**Comment by hnaderi** [comment]
> Oh, I was referring to the Org Mode docs. :smile:

 Oh!  I was in the wrong context then. :laughing: 

So, I continue with affiliate project.

**Comment by rossabaker** [comment]
@typelevel/steering: please vote with reaction on the issue. :+1: for yes, :-1: for no, :eyes: for abstain.  

I'll leave it open three business days (through Wednesday, March 22) and until quorum is reached.

**Comment by rossabaker** [comment]
Approved.  Quorum is 7 and majority is 7 :+1:'s, and we have 8 :+1:'s.  #86 is the next steps to get it on the site and toot the good news.
