### ISSUE TITLE
Project Submission: Edomata

### ISSUE THREAD

**Issue by hnaderi** [typelevel/governance#84]
### Project Name
[Edomata](https://github.com/hnaderi/edomata)

### Project Short Description
Event-driven automata for Scala, Scala.js and scala native

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

### Additional Notes
This project focuses on providing a toolkit for creating event-sourced and/or CQRS style applications in a purely functional way, its core is built on top of cats and also includes an extensible backend built on top of cats effect.
It also contains storage drivers using both doobie and skunk, that are completely interchangeable. Storage drivers are completely extensible.

I thought this project would be a nice fit for an affiliate project, as it is completely built on top of typelevel ecosystem and follows and encourages the same kind of mindset.

**Comment by jducoeur** [comment]
Very neat -- having done a lot with event sourcing in the Akka Cluster Sharding mode, it's fascinating to see this different decomposition!

**Comment by rossabaker** [comment]
Interesting stuff.  Same question as #83: does this have a declared Code of Conduct?

**Comment by hnaderi** [comment]
I just added a CoC on this one too. https://github.com/typelevel/governance/issues/83#issuecomment-1474759308

**Comment by rossabaker** [comment]
Thanks!  That ticks all the boxes for me, at least.

I'll open the vote along with #83, once we've reconfirmed that these are affiliate applications.

**Comment by rossabaker** [comment]
@typelevel/steering: please vote with reaction on the issue. :+1: for yes, :-1: for no, :eyes: for abstain.  

I'll leave it open three business days (through Wednesday, March 22) and until quorum is reached.

**Comment by rossabaker** [comment]
Approved.  Quorum is 7 and majority is 7 :+1:'s, and we have 7 :+1:'s.  #87 is the next steps.

**Comment by tpolecat** [comment]
I can still see this, btw. I need to be removed from a list somewhere.

Also hello.

**Comment by rossabaker** [comment]
Hello!  This repo is public.  Everyone can see it.  But you can unwatch it up top.
