### ISSUE TITLE
Project Submission: Catapult

### ISSUE THREAD

**Issue by bplommer** [typelevel/governance#85]
### Project Name
Catapult (https://github.com/bplommer/catapult)

### Project Short Description
A thin wrapper for the [Launch Darkly Java server SDK](https://github.com/launchdarkly/java-server-sdk) using cats-effect and fs2.

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [X] Organization Project
- [ ] Affiliate Project

### Additional Notes
This currently exposes a small subset of the Java SDK's functionality - there is scope to:
- expose more functionality from the Java SDK
- add support for server-side ScalaJS, backed by the Javascript server SDK
- add support for client-side ScalaJS
- introduce the concept of a codec for reading feature flags to arbitrary types
- introduce a thicker representation of "feature flag", encapsulating feature key, default value and codec
- add a Scala-idiomatic API for constructing evaluation contexts 
- ???

**Comment by rossabaker** [comment]
Looks useful to me.

I believe this is would be the first Typelevel Organization project that exists solely in support of a commercial offering.  I don't have a problem with that: this project and its dependencies are Open Source, and it's something many of us will need.  I also don't imagine myself personally putting much effort into it until and unless I'm a client.  Ben's a known good maintainer, but if he gets busy or loses interest, how likely is anyone to pick up the pieces?

(After that devil's advocacy, I'm still inclined to vote yes... just curious what others think.)

**Comment by jducoeur** [comment]
It's a good question. I'm also favorably inclined, having been working with LD until recently, but we should think about the ramifications.  I'd want to make sure that the library has enough test harness (and/or documentation) so that a non-specialist can be confident that it's still working when things update and we need a new release.  In particular, is it possible to test it without a paid LD license?

I'd probably say yes, but it's worth pondering...

**Comment by bplommer** [comment]
> Ben's a known good maintainer, but if he gets busy or loses interest, how likely is anyone to pick up the pieces?

Good question. I'll ask around to see if any colleagues are interested in getting involved.

>  I'd want to make sure that the library has enough test harness (and/or documentation) so that a non-specialist can be confident that it's still working when things update and we need a new release. In particular, is it possible to test it without a paid LD license?

Yes - the LD SDK provides a `TestData` harness for mocking out results of flag evaluation calls in unit testing. This project doesn't have any tests involving real remote calls, but the SDK it wraps does so I don't see that as a problem.

That said, there's definitely scope to add some documentation.

**Comment by bplommer** [comment]
@averymcnab has volunteered to join as an additional maintainer, and I can strongly vouch for them.

**Comment by rossabaker** [comment]
@typelevel/steering Please vote :+1:, :-1:, or :eyes: above.  Will be open three business days (Monday, March 27) and until quorum is reached.  And of course, continue to ask questions here if you have any...

**Comment by rossabaker** [comment]
@typelevel/steering bump

**Comment by rossabaker** [comment]
Approved with a quorum of at least 7 (got 7) and affirmative vote of at least 3/4 (got 100%).  Migration steps can be tracked in #88.
