### ISSUE TITLE
Migrating: edomata

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#87]
## Migration Checklist

Project Submission Issue: #84

### For All Projects:

- [x] Add project to the site by [adding an entry to the projects.yml file](https://github.com/typelevel/typelevel.github.com/blob/development/_data/projects.yml)

### Announcements

These steps are optional but encouraged.

- [ ] Write a blog post announcing the change
- [x] Post to our social channels (Twitter, Mastodon)

**Comment by rossabaker** [comment]
Added to the site and [tooted](https://fosstodon.org/@typelevel/110080288405544887).  I'm not sure whether we're still tweeting.

**Comment by jducoeur** [comment]
We should probably decide if we want to tweet any more.  I'm willing to interact with Twitter if the community feels it necessary, but I'm not going to be the one to motivate that at this point.  (IMO, Twitter has become enough of a swamp that I would kind of prefer for it to simply die.)

**Comment by rossabaker** [comment]
Nobody has claimed the Twitter.  Blogs on this (and Lepus) are welcome, but optional.  Closing.
