### ISSUE TITLE
Migrating: Catapult

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#88]
## Migration Checklist

Project Submission Issue: #85 

### For Organization Projects:

- [x] Create a team for the repo with maintainer as team member
- [x] After repo transfer, add repo with write permissions to the created team

### For All Projects:

- [x] Add project to the site by [adding an entry to the projects.yml file](https://github.com/typelevel/typelevel.github.com/blob/development/_data/projects.yml)

### Announcements

These steps are optional but encouraged.

- [ ] Write a blog post announcing the change
- [x] Post to our social channels (Twitter, Mastodon)

**Comment by rossabaker** [comment]
I created the new team and invited the two maintainers.  Once they accept and transfer the repo, we will add the repo to the team.

**Comment by bplommer** [comment]
I’ve transferred the repo to the Typelevel org. What’s the process for setting it up to publish to the TL maven org?

**Comment by rossabaker** [comment]
Credentials should be exposed to your GitHub Actions already, and I see you're already using sbt-typelevel.  Once `organization` is set to `org.typelevel`, I think it will just work when you push a tag.  You can also configure sbt-typelevel to publish snapshots on certain branches.

I tend to be a strong proponent of changing the top-level Scala package name whenever the Maven organization changes (i.e., `catapult` -> `org.typelevel.catapult`).  If you don't, org.typelevel Catapult won't evict io.github.bplommer Catapult and can lead to classloader roulette.  Since this is a relatively new project, you might be able to leave it alone and just give early adopters a heads up.  That's your call.

**Comment by bplommer** [comment]
Ah yes - I've changed the base package to `org.typelevel.catapult` and successfully published under the Typelevel org. I've also opened a [PR to update projects.yml](https://github.com/typelevel/typelevel.github.com/pull/438). Thanks for the help!

**Comment by rossabaker** [comment]
I set myself a reminder to toot the good news on Monday, when more people might be paying attention than late on a Friday.

**Comment by rossabaker** [comment]
[Tooted](https://fosstodon.org/@typelevel/110214875553675304).
