### ISSUE TITLE
Project Submission: endless4s

### ISSUE THREAD

**Issue by jchapuis** [typelevel/governance#89]
### Project Name
endless4s

### Project Short Description
Sharded and event-sourced entities for Cats Effect

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [ ] Organization Project
- [x] Affiliate Project

### Additional Notes
[endless4s](https://endless4s.github.io/) is a Scala library to describe sharded and event-sourced entities using tagless-final algebras, running with built-in implementations for Akka.

**Comment by rossabaker** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 for abstain.

I'll leave it open three business days (through Monday, April 10) and until quorum is reached.

**Comment by rossabaker** [comment]
Looks nice.  A couple questions:

1. Is there a code of conduct?  Another recent affiliate project added one [like this](https://github.com/hnaderi/lepus/blob/main/CODE_OF_CONDUCT.md).
2. Do you have a plan with the Akka licensing change?  Are you going to stick with 2.6 indefinitely, or look at Pekko, or provide multiple backends?

**Comment by jchapuis** [comment]
@rossabaker thanks for the consideration and sorry for the delay 🐰, good idea I'll add the code of conduct

regarding Akka the project does not rely on newer, OSS-breaking versions. The akka runtime project has a `Provided` dependency to the minimum required Akka version for proper operation. 

We indeed plan on adding a back-end for Pekko when it hits a first release. It's actually one advantage when using the lib, as it limits the number of direct imports to Akka namespaces (essentially shielding the entire algebra).

**Comment by rossabaker** [comment]
Awesome.  I like the pluggable design.

We need two more responses for quorum. /cc @typelevel/steering

**Comment by rossabaker** [comment]
Approved with a quorum of at least 7 (got 7) and affirmative vote of at least 3/4 (got 100%). Migration steps can be tracked in #92.
