### ISSUE TITLE
Project Submission: Skunk and Natchez

### ISSUE THREAD

**Issue by mpilquist** [typelevel/governance#94]
### Project Name

Skunk and Natchez

### Project Short Description

Skunk is a library for working with Postgres databases built on the Typelevel stack. Natchez provides a cats-effect based abstraction layer for distributed tracing.

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [x] Organization Project
- [ ] Affiliate Project

### Project Management

Typelevel projects are required to have an appropriate Code of Conduct. The [Scala Code of Conduct](https://typelevel.org/code-of-conduct) is a good option, but not specifically required. Before submitting a project for inclusion, please ensure that a pointer to its Code of Conduct is clearly linked from its README, CODE_OF_CONDUCT.md, or website.

- [x] This project's Code of Conduct can be found at https://github.com/typelevel/.github/blob/main/CODE_OF_CONDUCT.md

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria). Please make sure that the project's license is on the approved list.

- [x] This project's license can be found at https://github.com/typelevel/skunk/blob/main/LICENSE and https://github.com/typelevel/natchez/blob/main/LICENSE

### Additional Notes

I've been maintaining these projects for a few quarters now. Rob recently transferred these to the Typelevel organization in order to allow more control of repository settings, etc. I should have opened a ticket first. If these aren't accepted as org projects, I'll transfer them to a new organization.

**Comment by rossabaker** [comment]
@typelevel/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.

Voting is open three business days (through Thursday, April 20) and until quorum (7) is reached.

**Comment by rossabaker** [comment]
Quorum (needs 7, got 7) is reached, and vote is affirmed (needs 3/4, got 100%).  The usual tasks are tracked in #95 and #96.
