### ISSUE TITLE
Migrating: Skunk

### ISSUE THREAD

**Issue by rossabaker** [typelevel/governance#96]
## Migration Checklist

Project Submission Issue: #94 

### For Organization Projects:

- [x] Create a team for the repo with maintainer as team member
- [x] After repo transfer, add repo with write permissions to the created team

### For All Projects:

- [x] Add project to the site by [adding an entry to the projects.yml file](https://github.com/typelevel/typelevel.github.com/blob/development/_data/projects.yml)

### Announcements

These steps are optional but encouraged.

- [ ] Write a blog post announcing the change
- [x] Post to our social channels (Twitter, Mastodon)

**Comment by valencik** [comment]
Added to site in https://github.com/typelevel/typelevel.github.com/pull/443
