### ISSUE TITLE
Project Submission: Twiddles

### ISSUE THREAD

**Issue by mpilquist** [typelevel/governance#98]
### Project Name

Twiddles - https://github.com/typelevel/twiddles

### Project Short Description

Micro-library for building effectful protocols

### Project Type
In accordance with the [Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria), I am proposing the project be a:

- [x] Organization Project
- [ ] Affiliate Project

### Project Management

Typelevel projects are required to have an appropriate Code of Conduct. The [Scala Code of Conduct](https://typelevel.org/code-of-conduct) is a good option, but not specifically required. Before submitting a project for inclusion, please ensure that a pointer to its Code of Conduct is clearly linked from its README, CODE_OF_CONDUCT.md, or website.

- [x] This project's Code of Conduct can be found at https://github.com/typelevel/twiddles/blob/main/CODE_OF_CONDUCT.md

Similarly, Typelevel projects must have an appropriate license, as specified in [the Typelevel Charter](https://github.com/typelevel/governance/blob/main/CHARTER.md#8-project-criteria). Please make sure that the project's license is on the approved list.

- [x] This project's license can be found at https://github.com/typelevel/twiddles/blob/main/LICENSE

### Additional Notes

Generalization of syntax used in scodec and skunk. Will become a dependency of skunk in next release.

**Comment by rossabaker** [comment]
https://github.com/orgs/typelevel/teams/steering: please vote with reaction on the issue. 👍 for yes, 👎 for no, 👀 to abstain.

Voting is open three business days (through Wednesday, April 26) and until quorum (7) is reached.

**Comment by rossabaker** [comment]
Pretty easy yes from me, for its own quality and its pending position in the dependency tree.

**Comment by rossabaker** [comment]
@typelevel/steering: this is still just one short of quorum...

**Comment by rossabaker** [comment]
Well, that was fast.  Approved with a quorum (7) and at least 3/4 (unamious) vote.
